version: 2.1

# TODO(DP): the following context declaration does not appear to be working
context: FusionDB_images

executors:
  node14-exist:
    docker:
      - image: 'cypress/base-14'
        auth:
          username: duncdrum
          password: $DOCKER_TMP_PW  
      - image: 'existdb/existdb:latest'
        auth:
          username: duncdrum
          password: $DOCKER_TMP_PW


# see https://circleci.com/developer/orbs/orb/cypress-io/cypress
orbs:
  cypress: cypress-io/cypress@1.28.0
# TODO(DP): There is a bug here somewhere as we can run neither with nor without authentication creds. 
# executors:
#   node12-exist:
#     docker:
#       - image: 'cypress/base-14'
        # auth:
        #   username: duncdrum
        #   password: $DOCKER_TMP_PW  
      # - image: 'existdb/existdb:latest'
        # auth:
        #   username: duncdrum
        #   password: $DOCKER_TMP_PW

workflows:
  build:
    jobs:
      - cypress/run:
          executor: node14-exist
          context: FusionDB_images
          yarn: true
          post-checkout:
            - run:  |
                apt-get update 
                apt-get --yes install libx11-dev libxkbfile-dev
                wget https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_20.10.6~3-0~ubuntu-bionic_amd64.deb
                dpkg -i *.deb
            - setup_remote_docker:
                version: 20.10.2
                docker_layer_caching: false    
          start: cd browser-app && yarn theia start --hostname 0.0.0.0 --port 3000
          post-install:
            - run:  |
                wget https://github.com/evolvedbinary/fusion-studio-api/releases/download/1.2.0/fusion-studio-api-1.2.0.xar
                docker create -v /exist/autodeploy --name pkg alpine:3.4 /bin/true
                docker cp *.xar pkg:/exist/autodeploy                
                docker run -dit -p 8080:8080 --name exist-ci --rm --volumes-from pkg existdb/existdb:latest
            - run: curl --retry 5 http://localhost:8080          
          # TODO(DP): 
          #   - see #379 use e.g. -e API_PORT=8080, or context/executor declaration to set working (!) env variables
          #   - s.a. to sidestep auth bug: docker login repo.evolvedbinary.com:9543 -u FDB_NIGHTLY_DOCKER_USER -p FDB_NIGHTLY_DOCKER_PASS
          command: npx cypress run
          no-workspace: false                     
          record: true
          store_artifacts: true
          tags: 'eXist-db,latest'

